[2025-09-25T09:30:07.437+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-25T09:30:07.452+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_pipeline_orchestration.check_analytics_api scheduled__2025-09-25T09:15:00+00:00 [queued]>
[2025-09-25T09:30:07.456+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_pipeline_orchestration.check_analytics_api scheduled__2025-09-25T09:15:00+00:00 [queued]>
[2025-09-25T09:30:07.456+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-25T09:30:07.474+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_analytics_api> on 2025-09-25 09:15:00+00:00
[2025-09-25T09:30:07.500+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=959) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-25T09:30:07.501+0000] {standard_task_runner.py:64} INFO - Started process 964 to run task
[2025-09-25T09:30:07.527+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_pipeline_orchestration', 'check_analytics_api', 'scheduled__2025-09-25T09:15:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_orchestration.py', '--cfg-path', '/tmp/tmprhrwk39l']
[2025-09-25T09:30:07.566+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask check_analytics_api
[2025-09-25T09:30:07.677+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_pipeline_orchestration.check_analytics_api scheduled__2025-09-25T09:15:00+00:00 [running]> on host 32ce42b7fa38
[2025-09-25T09:30:07.814+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_pipeline_orchestration' AIRFLOW_CTX_TASK_ID='check_analytics_api' AIRFLOW_CTX_EXECUTION_DATE='2025-09-25T09:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-25T09:15:00+00:00'
[2025-09-25T09:30:07.818+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-25T09:30:07.901+0000] {logging_mixin.py:188} INFO - ‚ùå Analytics API check failed: HTTPConnectionPool(host='analytics-api', port=8000): Max retries exceeded with url: /health (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffffabb17950>: Failed to resolve 'analytics-api' ([Errno -2] Name or service not known)"))
[2025-09-25T09:30:07.902+0000] {python.py:237} INFO - Done. Returned value was: API not available
[2025-09-25T09:30:07.902+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-25T09:30:07.913+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_pipeline_orchestration, task_id=check_analytics_api, run_id=scheduled__2025-09-25T09:15:00+00:00, execution_date=20250925T091500, start_date=20250925T093007, end_date=20250925T093007
[2025-09-25T09:30:07.930+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-25T09:30:07.935+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
